projects:
  eform:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/services/graphql/Interventions.service.ts
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
